Detail page commit list diffstat
CATcher-org/WATcher pull request #133
Opened 2023-04-10 12:13 UTC by Eclipse-Dominator

### Summary:
Partially addresses #69, depends on #132 

### Changes Made:
- Adds diffstats component to display line additions and deletions
- Adds RSQ data structures to enable fast RSQ queries
- Calculates cumulative stats in the commits
- Adds the ability to check cumulative stats across multiple commits
- Show currently shown commits

### Commit Message:

```
The commit list currently doesn't display line changes
Let's display the line change per commit as well as the cumulative line changes

- Adds diffstats component to display line additions and deletions
- Adds RSQ data structures to enable fast RSQ queries
- Calculates cumulative stats in the commits
- Adds the ability to check cumulative stats across multiple commits
- Show currently shown commits
```

2023-07-10 04:58 UTC, gycgabriel requested changes

2023-07-10 04:58 UTC, gycgabriel commented on src/app/user-detail-viewer/commit-list/commit-list.component.ts
> +}
Create a model.ts for this

2023-07-10 04:58 UTC, gycgabriel commented on src/app/user-detail-viewer/commit-list/commit-list.component.ts
> +      prefixArr[commitToIndex(commit)].add(new CumulativeStats(commit));
I checked your `dateToIndex` function, it uses a sparse array. Tested on cs2103, it works fine without any jitters. We can go with this. 👍

2023-07-10 05:00 UTC, gycgabriel reviewed
Tested and works well! Some comments to look into.

Found a bug when switching repo on detail page, will need to disable that button.

2023-07-10 05:03 UTC, gycgabriel commented on src/app/user-detail-viewer/commit-list/commit-list.component.ts
> +      prefixArr[commitToIndex(commit)].add(new CumulativeStats(commit));
For reference, the average size of the array will be from 40-50

2023-07-12 04:05 UTC, Eclipse-Dominator commented on src/app/core/models/datastructure/rsq.model.ts
> +  constructor(private arr: T[], private identity: () => T) {
having an identity function here is mainly cos the accumulator interface suggests that the object is mutable. To perform a range query, we either need to create an "identity" accumulator or have way to clone the accumulator.

2023-07-12 05:48 UTC, Eclipse-Dominator commented
> Tested and works well! Some comments to look into.
> 
> Found a bug when switching repo on detail page, will need to disable that button in the future

This issue appeared after I switched to using phases for page swap. I think I will make a separate PR in the Profile Page branch to address this before merging it.

2023-07-12 05:51 UTC, Eclipse-Dominator commented on src/app/core/models/datastructure/rsq.model.ts
> +      arr[i].add(arr[i - 1]);
I made the constructor take in an array that is to be used as the prefix sum so I think I will mention it in the documentation.

2023-07-14 01:52 UTC, gycgabriel approved these changes
LGTM!

2023-07-14 12:17 UTC, merged