Create tests for Milestone service
CATcher-org/WATcher pull request #303
Opened 2024-03-15 06:22 UTC by MadLamprey

### Summary:

Fixes part of #87

#### Type of change:
- 🧪 Tests Update

### Changes Made:

- Added test cases for `milestone.service.ts`

### Proposed Commit Message:

```
Create tests for Milestone service

Currently, there are no tests written for Milestone service, which are necessary to ensure it is functioning as expected.

Let's create tests for milestone service.
```
###

2024-03-15 09:47 UTC, NereusWB922 submitted a review, later dismissed
LGTM!

2024-03-15 14:42 UTC, luminousleek requested changes
Small nit, other than that the code LGTM. Please wrap your commit message at 72 characters too.

2024-03-15 14:42 UTC, luminousleek commented on tests/services/milestone.service.spec.ts
> +        expect(milestone instanceof Milestone).toBeTrue();
Can use the jasmine matcher `toBeInstanceOf` here.

2024-03-20 13:06 UTC, luminousleek approved these changes
LGTM! Thanks for making the change.

2024-03-25 05:11 UTC, merged