Setup grouping strategy and service
CATcher-org/WATcher pull request #308
Opened 2024-03-19 04:40 UTC by NereusWB922

### Summary:

Fixes part of #306 

#### Type of change:

- ✨ New Feature/ Enhancement

### Changes Made:

**This pr only include setup for GroupingService, will integrate GroupingService in the separate pr**

- Introduce Group interface that represents group used for categorization
- Refactor GithubUser as class and implement Group Interface
- Introduce GroupingStrategy interface to represent groupings logic based on different criteria (Follow Strategy design pattern)
- Implement Grouping Context Service that responsible for managing the grouping, includes retrieve grouped data and all applicable groups based on current GroupingStrategy.

### Proposed Commit Message:

```
Setup Grouping Strategy and Service

Implement GroupBy feature to allow users group the issues/prs
based on different criteria such as milestone, status and etc.

Let's setup the Grouping Strategy and Service.
```

2024-03-20 12:56 UTC, nknguyenhc requested changes
Nice attempt on the new service!

2024-03-20 12:56 UTC, nknguyenhc commented on src/app/core/models/github-user.model.ts
> +
This can be shortened to:
```ts
constructor(rawData: RawGithubUser) {
  Object.assign(this, rawData);
}
```

2024-03-20 12:56 UTC, nknguyenhc commented on src/app/core/models/github-user.model.ts
> +export class GithubUser implements Group {
Shouldn't `GithubUser` implements interface `RawGithubUser` as well?

2024-03-20 12:56 UTC, nknguyenhc commented on src/app/core/models/github-user.model.ts
> +  } as RawGithubUser);
I don't think this type casting is necessary? As long as the object has all the keys, there is no need to do type casting.

2024-03-20 12:56 UTC, nknguyenhc commented on src/app/core/services/grouping/grouping-strategy.interface.ts
Shouldn't this file be under `models` instead?

2024-03-20 12:56 UTC, nknguyenhc commented on src/app/core/services/grouping/grouping-strategy.interface.ts
> +  shouldBeInHiddenGroupsIfEmpty(group: Group): boolean;
Would a better name be `isInHiddenList`?

2024-03-20 12:56 UTC, nknguyenhc commented on src/app/core/services/grouping/grouping-context.service.ts
> +import { MilestoneGroupingStrategy } from './milestone-grouping-strategy.service';
There isn't a corresponding file for this declaration.

2024-03-20 13:24 UTC, NereusWB922 commented on src/app/core/services/grouping/grouping-strategy.interface.ts
I'm not sure about this. Since the grouping strategy is a service, shouldn't the interface also be under the service folder?

2024-03-20 14:02 UTC, NereusWB922 commented
> Nice attempt on the new service!

Thanks for the review! I just committed new changes based on your comments. Just unsure about the which folder should I store the group strategy interface.

2024-03-21 00:51 UTC, nknguyenhc commented on src/app/core/services/grouping/grouping-strategy.interface.ts
Since this interface is only used in the service, I think it should be fine leaving it here.

2024-03-21 00:53 UTC, nknguyenhc approved these changes
LGTM!

2024-03-22 15:09 UTC, merged