Fix bottom shadow of columns
CATcher-org/WATcher pull request #357
Opened 2024-04-04 14:33 UTC by Arif-Khalid

### Summary:

Fixes #354 

#### Type of change:

- 🐛 Bug Fix

### Changes Made:

- Refactor CSS style for bottom shadow into new class on mat-paginator at the foot of columns

### Screenshots:
Before the change
![image](https://github.com/CATcher-org/WATcher/assets/88131400/5124c933-002a-4386-9c76-b7859c3acde4)
After the change
![image](https://github.com/CATcher-org/WATcher/assets/88131400/885d2a79-9de7-4fc6-8aca-4630eb079df6)

### Proposed Commit Message:

```
The bottom shadow of each column is sticks
to the column as the user scrolls.

This is unintuitive as user expects the shadow
to stay at the foot of the column.

Let's refactor the CSS to ensure the shadow 
stays at the foot of the columns as they scroll.
```

<details><summary>
<h3>Checklist:</h3>
</summary>

- [x] I have tested my changes thoroughly.
- [ ] I have created tests for any new code files created in this PR or provided a link to a issue/PR that addresses this.
- [x] I have added or modified code comments to improve code readability where necessary.
- [ ] I have updated the project's documentation as necessary.

</details>

2024-04-04 14:45 UTC, damithc commented
@Arif-Khalid This is clearly a bug. So, let's write the commit message from that perspective. The current one sounds like we are tweaking the design, not fixing a bug.
Also, refactoring should not change behavior. So, this should not be called a refactoring.

Example:
```
Prevent bottom shadow from sticking to column
---------------------------------------------------
The shadow at the bottom of a column sticks to the column content
as the column is scrolled.

Let's fix this bug so that the shadow stays in place during scrolling.
```

2024-04-04 14:48 UTC, Arif-Khalid commented
> @Arif-Khalid This is clearly a bug. So, let's write the commit message from that perspective. The current one sounds like we are tweaking the design, not fixing a bug. Also, refactoring should not change behavior. So, this should not be called a refactoring.
> 
> Example:
> 
> ```
> Prevent bottom shadow from sticking to column
> ---------------------------------------------------
> The shadow at the bottom of a column sticks to the column content
> as the column is scrolled.
> 
> Let's fix this bug so that the shadow stays in place during scrolling.
> ```

Understood. I have updated my PRs appropriately.

2024-04-05 05:49 UTC, NereusWB922 requested changes
Bottom shadow should be hidden when reach the end of the list.

2024-04-08 08:34 UTC, NereusWB922 approved these changes
LGTM!

2024-04-10 14:19 UTC, merged