Fix reset of filters on label fetch
CATcher-org/WATcher pull request #374
Opened 2024-04-15 06:18 UTC by Arif-Khalid

### Summary:

Fixes #372 

#### Type of change:

- 🐛 Bug Fix

### Changes Made:

- Change type of preset views to partial filters
- Add default filter separate from preset views
- Configure load from url to align with new behaviour

### Proposed Commit Message:

```
There is a bug where filters are reset when 
labels are fetched.

This bug can cause sudden, unprompted
changes to filters.

Let's change the filter's service behaviour
when fetching labels to stop resetting filters.
```

<details><summary>
<h3>Checklist:</h3>
</summary>

- [x] I have tested my changes thoroughly.
- [ ] I have created tests for any new code files created in this PR or provided a link to a issue/PR that addresses this.
- [x] I have added or modified code comments to improve code readability where necessary.
- [ ] I have updated the project's documentation as necessary.

</details>

2024-04-15 14:07 UTC, nknguyenhc requested changes
First time opening the app and viewing `AY2324S1-CS2103T-T08-2/tp` should have default preset view being "Currently active", however default preset view is now "Custom".

2024-04-15 14:10 UTC, nknguyenhc reviewed
Besides, pressing the "Currently active" button from the preset view dropdown should change sort property back to "Status", but currently, sort property does not change accordingly.

2024-04-18 02:41 UTC, Arif-Khalid commented
> Besides, pressing the "Currently active" button from the preset view dropdown should change sort property back to "Status", but currently, sort property does not change accordingly.

It was my understanding that changing the sort does not change the preset view to custom, similar to how changing the title filter does not change the preset view to custom. It then follows that changing the preset view to currentlyActive does not change the sort to a default value since changing the sort does not change the preset view status.

2024-04-18 02:46 UTC, Arif-Khalid commented
> First time opening the app and viewing `AY2324S1-CS2103T-T08-2/tp` should have default preset view being "Currently active", however default preset view is now "Custom".

Good catch. I have fixed this behaviour.

2024-04-18 13:27 UTC, Arif-Khalid commented
Changes have been made to specify 2-way binding for sort filter and preset view and 1 way binding for title, itemsPerPage filters and preset view.
To elaborate, when changing sort filters, preset view is changed to custom. When selecting preset view, a default sort is applied.
When changing title or itemsPerPage filters, preset view is not changed to custom. When selecting preset view, a default title and itemsPerPage is applied.

2024-04-19 02:03 UTC, nknguyenhc approved these changes
LGTM! Everything works well.

2024-04-19 09:42 UTC, merged